openapi: 3.0.0
info:
  version: '2022-11-28'
  x-release: v4
  title: Amazon Omics AnnotationStore AnnotationStores API
  description: This is the <i>AWS HealthOmics API Reference</i>. For an introduction to the service, see <a href="https://docs.aws.amazon.com/omics/latest/dev/">What is AWS HealthOmics?</a> in the <i>AWS HealthOmics User Guide</i>.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: omics
  x-aws-signingName: omics
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/omics-2022-11-28.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://omics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Omics multi-region endpoint
- url: https://omics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Omics multi-region endpoint
- url: http://omics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Omics endpoint for China (Beijing) and China (Ningxia)
- url: https://omics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Omics endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: AnnotationStores
paths:
  /annotationStores:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListAnnotationStores
      description: Retrieves a list of annotation stores.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAnnotationStoresResponse'
        '480':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '481':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '484':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
      parameters:
      - name: maxResults
        in: query
        required: false
        description: The maximum number of stores to return in one page of results.
        schema:
          type: integer
          minimum: 1
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: Specify the pagination token from a previous request to retrieve the next page of results.
        schema:
          type: string
          minLength: 1
          maxLength: 10000
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  description: IDs of stores to list.
                  type: array
                  items:
                    $ref: '#/components/schemas/ResourceIdentifier'
                  minItems: 1
                  maxItems: 20
                filter:
                  description: A filter for annotation stores.
                  type: object
                  properties:
                    status:
                      allOf:
                      - $ref: '#/components/schemas/StoreStatus'
                      - description: A status to filter on.
      summary: Amazon HealthOmics List Annotation Stores
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - AnnotationStores
components:
  schemas:
    Arn:
      type: string
      pattern: 'arn:([^: ]*):([^: ]*):([^: ]*):([0-9]{12}):([^: ]*)'
      minLength: 20
      maxLength: 2048
    ResourceNotFoundException: {}
    CreationTime:
      type: string
      format: date-time
    StoreDescription:
      type: string
      minLength: 0
      maxLength: 500
    ReferenceArn:
      type: string
      pattern: arn:.+
      minLength: 1
      maxLength: 127
    StoreFormat:
      type: string
      enum:
      - GFF
      - TSV
      - VCF
    ReferenceItem:
      type: object
      properties:
        referenceArn:
          allOf:
          - $ref: '#/components/schemas/ReferenceArn'
          - description: The reference's ARN.
      description: A genome reference.
    ListAnnotationStoresResponse:
      type: object
      properties:
        annotationStores:
          allOf:
          - $ref: '#/components/schemas/AnnotationStoreItems'
          - description: A list of stores.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A pagination token that's included if more results are available.
    ResourceId:
      type: string
      pattern: '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
    AnnotationStoreItem:
      type: object
      required:
      - id
      - reference
      - status
      - storeArn
      - name
      - storeFormat
      - description
      - sseConfig
      - creationTime
      - updateTime
      - statusMessage
      - storeSizeBytes
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/ResourceId'
          - description: The store's ID.
        reference:
          allOf:
          - $ref: '#/components/schemas/ReferenceItem'
          - description: The store's genome reference.
        status:
          allOf:
          - $ref: '#/components/schemas/StoreStatus'
          - description: The store's status.
        storeArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The store's ARN.
        name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The store's name.
        storeFormat:
          allOf:
          - $ref: '#/components/schemas/StoreFormat'
          - description: The store's file format.
        description:
          allOf:
          - $ref: '#/components/schemas/StoreDescription'
          - description: The store's description.
        sseConfig:
          allOf:
          - $ref: '#/components/schemas/SseConfig'
          - description: The store's server-side encryption (SSE) settings.
        creationTime:
          allOf:
          - $ref: '#/components/schemas/CreationTime'
          - description: The store's creation time.
        updateTime:
          allOf:
          - $ref: '#/components/schemas/UpdateTime'
          - description: When the store was updated.
        statusMessage:
          allOf:
          - $ref: '#/components/schemas/StatusMessage'
          - description: The store's status message.
        storeSizeBytes:
          allOf:
          - $ref: '#/components/schemas/Long'
          - description: The store's size in bytes.
      description: An annotation store.
    ResourceIdentifier:
      type: string
      minLength: 1
      maxLength: 50
    StoreStatus:
      type: string
      enum:
      - CREATING
      - UPDATING
      - DELETING
      - ACTIVE
      - FAILED
    AnnotationStoreItems:
      type: array
      items:
        $ref: '#/components/schemas/AnnotationStoreItem'
    EncryptionType:
      type: string
      enum:
      - KMS
    ThrottlingException: {}
    String:
      type: string
    StatusMessage:
      type: string
      minLength: 0
      maxLength: 1000
    SseConfig:
      type: object
      required:
      - type
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/EncryptionType'
          - description: The encryption type.
        keyArn:
          allOf:
          - $ref: '#/components/schemas/SseConfigKeyArnString'
          - description: An encryption key ARN.
      description: Server-side encryption (SSE) settings for a store.
    ValidationException: {}
    SseConfigKeyArnString:
      type: string
      pattern: '.*arn:([^: ]*):([^: ]*):([^: ]*):([0-9]{12}):([^: ]*).*'
      minLength: 20
      maxLength: 2048
    AccessDeniedException: {}
    UpdateTime:
      type: string
      format: date-time
    InternalServerException: {}
    Long:
      type: integer
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/omics/
x-hasEquivalentPaths: true
