openapi: 3.0.0
info:
  version: '2022-11-28'
  x-release: v4
  title: Amazon Omics AnnotationStore Sequencestores API
  description: This is the <i>AWS HealthOmics API Reference</i>. For an introduction to the service, see <a href="https://docs.aws.amazon.com/omics/latest/dev/">What is AWS HealthOmics?</a> in the <i>AWS HealthOmics User Guide</i>.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: omics
  x-aws-signingName: omics
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/omics-2022-11-28.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://omics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Omics multi-region endpoint
- url: https://omics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Omics multi-region endpoint
- url: http://omics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Omics endpoint for China (Beijing) and China (Ningxia)
- url: https://omics.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Omics endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Sequencestores
paths:
  /sequencestores:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListSequenceStores
      description: Retrieves a list of sequence stores.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSequenceStoresResponse'
        '480':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '481':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '483':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '484':
          description: RequestTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestTimeoutException'
      parameters:
      - name: maxResults
        in: query
        required: false
        description: The maximum number of stores to return in one page of results.
        schema:
          type: integer
          minimum: 1
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: Specify the pagination token from a previous request to retrieve the next page of results.
        schema:
          type: string
          pattern: '[\p{L}||\p{M}||\p{Z}||\p{S}||\p{N}||\p{P}]+'
          minLength: 1
          maxLength: 6144
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  description: A filter for a sequence store.
                  type: object
                  properties:
                    name:
                      allOf:
                      - $ref: '#/components/schemas/SequenceStoreName'
                      - description: A name to filter on.
                    createdAfter:
                      allOf:
                      - $ref: '#/components/schemas/SyntheticTimestamp_date_time'
                      - description: The filter's start date.
                    createdBefore:
                      allOf:
                      - $ref: '#/components/schemas/SyntheticTimestamp_date_time'
                      - description: The filter's end date.
      summary: Amazon HealthOmics List Sequence Stores
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Sequencestores
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    SequenceStoreName:
      type: string
      pattern: '[\p{L}||\p{M}||\p{Z}||\p{S}||\p{N}||\p{P}]+'
      minLength: 1
      maxLength: 127
    S3Destination:
      type: string
      pattern: s3://([a-z0-9][a-z0-9-.]{1,61}[a-z0-9])/?((.{1,1024})/)?
    NextToken:
      type: string
      pattern: '[\p{L}||\p{M}||\p{Z}||\p{S}||\p{N}||\p{P}]+'
      minLength: 1
      maxLength: 6144
    ListSequenceStoresResponse:
      type: object
      required:
      - sequenceStores
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: A pagination token that's included if more results are available.
        sequenceStores:
          allOf:
          - $ref: '#/components/schemas/SequenceStoreDetailList'
          - description: A list of sequence stores.
    SyntheticTimestamp_date_time:
      type: string
      format: date-time
    SequenceStoreId:
      type: string
      pattern: '[0-9]+'
      minLength: 10
      maxLength: 36
    SequenceStoreDescription:
      type: string
      pattern: '[\p{L}||\p{M}||\p{Z}||\p{S}||\p{N}||\p{P}]+'
      minLength: 1
      maxLength: 255
    SequenceStoreDetailList:
      type: array
      items:
        $ref: '#/components/schemas/SequenceStoreDetail'
    RequestTimeoutException: {}
    ThrottlingException: {}
    EncryptionType:
      type: string
      enum:
      - KMS
    SequenceStoreDetail:
      type: object
      required:
      - arn
      - id
      - creationTime
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/SequenceStoreArn'
          - description: The store's ARN.
        id:
          allOf:
          - $ref: '#/components/schemas/SequenceStoreId'
          - description: The store's ID.
        name:
          allOf:
          - $ref: '#/components/schemas/SequenceStoreName'
          - description: The store's name.
        description:
          allOf:
          - $ref: '#/components/schemas/SequenceStoreDescription'
          - description: The store's description.
        sseConfig:
          allOf:
          - $ref: '#/components/schemas/SseConfig'
          - description: The store's server-side encryption (SSE) settings.
        creationTime:
          allOf:
          - $ref: '#/components/schemas/SyntheticTimestamp_date_time'
          - description: When the store was created.
        fallbackLocation:
          allOf:
          - $ref: '#/components/schemas/S3Destination'
          - description: ' An S3 location that is used to store files that have failed a direct upload. '
      description: Details about a sequence store.
    SseConfig:
      type: object
      required:
      - type
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/EncryptionType'
          - description: The encryption type.
        keyArn:
          allOf:
          - $ref: '#/components/schemas/SseConfigKeyArnString'
          - description: An encryption key ARN.
      description: Server-side encryption (SSE) settings for a store.
    ValidationException: {}
    SseConfigKeyArnString:
      type: string
      pattern: '.*arn:([^: ]*):([^: ]*):([^: ]*):([0-9]{12}):([^: ]*).*'
      minLength: 20
      maxLength: 2048
    SequenceStoreArn:
      type: string
      pattern: arn:.+
      minLength: 1
      maxLength: 127
    AccessDeniedException: {}
    InternalServerException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/omics/
x-hasEquivalentPaths: true
